id: I13D3CF6A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:19:10+00:00'
last_modified: '2022-06-10T05:31:14.063469+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD234
  title: རང་བཞིན་སློབ་གསོའི་མན་ངག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    483A:
      image_group_id: I4PD4630
      title: Volume 1 of rang bzhin slob gso'i man ngag
      total_pages: 366
      order: 1
      base_file: 483A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
